@startuml
abstract class BaseState {
    + {abstract} Enter() : void
    + {abstract} Perform() : void
    + {abstract} Exit() : void
}
BaseState --> "npc" Npc
BaseState --> "stateMachine" StateMachine
@enduml
