using System;
using System.Collections.Generic;
using UnityEngine;

namespace FriWorld.Navigator
{
    /// <summary>
    /// Where the flight ends for each room code: a point on the Navigator navmesh in front of
    /// the room's door, on the side the path from the start reaches first. The start itself is
    /// not here — it is wherever the Navigator camera is placed in the scene.
    ///
    /// Generated by <c>Navigator → 2 — Bake Room Anchors</c>; do not edit by hand. Baked in the
    /// editor because the room containers and doors are only known by name there, and the web
    /// build strips parts of the building per platform.
    /// </summary>
    public class RoomAnchors : ScriptableObject
    {
        /// <summary>How far in front of the room's door the anchor stands (m).</summary>
        public const float DoorDistance = 1.6f;

        [Serializable]
        public struct Anchor
        {
            [Tooltip("Room code as people write it, e.g. RA101.")]
            public string code;

            [Tooltip("Point on the navmesh in front of the door.")]
            public Vector3 position;

            [Tooltip("Horizontal direction from the anchor towards the door.")]
            public Vector3 facing;
        }

        [Tooltip("Agent type the navmesh was baked for; paths are queried with the same one.")]
        public int agentTypeID;

        public List<Anchor> anchors = new List<Anchor>();

        /// <summary>"ra 101 ", "Ra101" and "RA101" all name the same room.</summary>
        public static string Normalize(string code)
        {
            return string.IsNullOrWhiteSpace(code) ? string.Empty : code.Replace(" ", "").Trim().ToUpperInvariant();
        }

        public bool TryGet(string code, out Anchor anchor)
        {
            string key = Normalize(code);
            foreach (var a in anchors)
            {
                if (a.code == key)
                {
                    anchor = a;
                    return true;
                }
            }

            anchor = default;
            return false;
        }
    }
}
