@startuml
!include .\\EventOnlyInteractable.puml
!include .\\InputManager.puml
!include .\\Interactable.puml
!include .\\InteractionEvent.puml
!include .\\Interactables\Collectible.puml
!include .\\Interactables\Door.puml
!include .\\Interactables\Keypad.puml
!include .\\NPC\Npc.puml
!include .\\NPC\Path.puml
!include .\\NPC\StateMachine.puml
!include .\\Player\Player.puml
!include .\\Player\PlayerInteract.puml
!include .\\Player\PlayerLook.puml
!include .\\Player\PlayerMotor.puml
!include .\\Questables\Questable.puml
!include .\\Questables\QuestItem.puml
!include .\\Questables\QuestPoint.puml
!include .\\NPC\Dialogue\DialogueManager.puml
!include .\\NPC\Quests\Quest.puml
!include .\\NPC\Quests\QuestLoader.puml
!include .\\NPC\Quests\QuestManager.puml
!include .\\NPC\States\BaseState.puml
!include .\\NPC\States\DialogueState.puml
!include .\\NPC\States\WonderState.puml
!include .\\Player\Navigation\Navigation.puml
!include .\\Player\Navigation\RoomData.puml
!include .\\Player\Navigation\RoomManager.puml
!include .\\Player\PlayerManagment\PlayerManagment.puml
!include .\\Player\UI\BaseUi.puml
!include .\\Player\UI\CodexUI.puml
!include .\\Player\UI\DialogueUI.puml
!include .\\Player\UI\JournalUI.puml
!include .\\Player\UI\NavigationUI.puml
!include .\\Player\UI\PlayerUI.puml
!include .\\Player\UI\StatsUI.puml
!include .\\Player\UI\TabUI.puml
!include .\\Player\UI\UIManager.puml
!include .\\Player\PlayerManagment\Journal\Journal.puml
!include .\\Player\PlayerManagment\Journal\QuestStatus.puml
@enduml
